### ISSUE TITLE
com.fasterxml.jackson.databind.exc.InvalidDefinitionException

### ISSUE THREAD

**Issue by amirh715** [eventuate-foundation/eventuate-common#117]
This is the exception I get when I try to create a domain event. My domain event has a user object with a `createdAt` property of type `LocalDateTime`. I guess the issue is with Eventuate. What should I do?
```
java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.LocalDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (through reference chain: com.domain.events.NewUserRegistered["user"]->com.domain.User["createdAt"])
	at io.eventuate.common.json.mapper.JSonMapper.toJson(JSonMapper.java:29)
	at io.eventuate.tram.events.common.EventUtil.makeMessageForDomainEvent(EventUtil.java:18)
	at io.eventuate.tram.events.publisher.DomainEventPublisherImpl.publish(DomainEventPublisherImpl.java:36)
	at io.eventuate.tram.events.publisher.DomainEventPublisherImpl.publish(DomainEventPublisherImpl.java:25)
```

This is my pom file:
```
<dependency>
	<groupId>io.eventuate.tram.core</groupId>
	<artifactId>eventuate-tram-spring-messaging</artifactId>
	<version>0.30.0.RELEASE</version>
</dependency>
<dependency>
	<groupId>io.eventuate.tram.core</groupId>
	<artifactId>eventuate-tram-spring-events</artifactId>
	<version>0.30.0.RELEASE</version>
</dependency>
<dependency>
	<groupId>io.eventuate.tram.core</groupId>
	<artifactId>eventuate-tram-spring-commands</artifactId>
	<version>0.30.0.RELEASE</version>
</dependency>
<dependency>
	<groupId>io.eventuate.tram.core</groupId>
	<artifactId>eventuate-tram-spring-producer-jdbc</artifactId>
	<version>0.30.0.RELEASE</version>
</dependency>
<dependency>
	<groupId>io.eventuate.tram.core</groupId>
	<artifactId>eventuate-tram-spring-events-publisher-starter</artifactId>
	<version>0.30.0.RELEASE</version>
</dependency>
```

**Comment by cer** [comment]
Configure 

https://github.com/eventuate-foundation/eventuate-common/blob/6fe5612f4f59943aac7c440b353f923f52a3aff4/eventuate-common-json-mapper/src/main/java/io/eventuate/common/json/mapper/JSonMapper.java#L14

It's public so you can register additional modules.
