### ISSUE TITLE
CircleCI Build #112 failure - java.lang.AssertionError: Row id should start from current time in milliseconds after migration (current time: 1607015506230, id: 15)

### ISSUE THREAD

**Issue by cer** [eventuate-foundation/eventuate-common#58]
```
java.lang.AssertionError: Row id should start from current time in milliseconds after migration (current time: 1607015506230, id: 15)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at io.eventuate.common.jdbc.tests.AbstractEventuateCommonJdbcOperationsTest.assertIdSequenceUsesCurrentTimeAsStartingValue(AbstractEventuateCommonJdbcOperationsTest.java:257)
	at io.eventuate.common.jdbc.tests.AbstractEventuateCommonJdbcOperationsTest.testGeneratedId(AbstractEventuateCommonJdbcOperationsTest.java:154)
	at io.eventuate.common.jdbc.tests.AbstractEventuateCommonJdbcOperationsTest.testGeneratedIdOfEventsTableRow(AbstractEventuateCommonJdbcOperationsTest.java:127)
	at io.eventuate.common.spring.jdbc.EventuateCommonJdbcOperationsTest.testGeneratedIdOfEventsTableRow(EventuateCommonJdbcOperationsTest.java:69)

```

**Comment by dartartem** [comment]
After commit https://github.com/eventuate-foundation/eventuate-common/commit/a3992109d00051ef0ae00b7769bbf15222e89077 that adds verification that mysql anchor event row is created,
test failed: 
```
testGeneratedIdOfEventsTableRow - io.eventuate.common.spring.jdbc.EventuateCommonJdbcOperationsTest
java.lang.AssertionError: expected:<1> but was:<0>
```
It means that row does not exist:

https://github.com/eventuate-foundation/eventuate-common/blob/wip-db-id-gen/mysql/4.initialize-database-db-id.sql#L37-L38

I see 2 possible reasons:
1. It is not created, for example because https://github.com/eventuate-foundation/eventuate-common/blob/wip-db-id-gen/mysql/9.initialization-completed.sh does not work properly
2. It was removed by some other test

**Comment by dartartem** [comment]
Looks like problem is in https://github.com/eventuate-foundation/eventuate-common/blob/master/eventuate-common-spring-jdbc/src/test/java/io/eventuate/common/spring/jdbc/SqlDialectIntegrationTest.java#L116

Sql dialect tests clear events table.

**Comment by dartartem** [comment]
https://github.com/eventuate-foundation/eventuate-common/pull/60/commits/1bebf08e1e86212b11331b293ed0861eb55b18b8 removes table clean up. Slightly modifies test assertion to work without clean up.
