### ISSUE TITLE
Quarkus does not support selecting database type at runtime

### ISSUE THREAD

**Issue by dartartem** [eventuate-foundation/eventuate-common#70]
### Problem

Database should be selected at the build time and it is not clear how to test applications over different databases

Spring example:

To test application over mysql and postgres we should define 2 properties files with database configs:

**application.properties**

```
spring.datasource.url=jdbc:mysql://${DOCKER_HOST_IP:localhost}/eventuate
spring.datasource.username=mysqluser
spring.datasource.password=mysqlpw
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
```

**application-postgres.properties**

```
spring.datasource.url=jdbc:postgresql://${DOCKER_HOST_IP:localhost}/eventuate
spring.datasource.username=eventuate
spring.datasource.password=eventuate
spring.datasource.driver-class-name=org.postgresql.Driver
```

So, mysql profile is used by default, postgres is activated by setting env variable SPRING_PROFILES_ACTIVE to postgres.

Quarkus also has support for profiles: https://quarkus.io/guides/config#configuration-profiles

According documentation, to achieve the same configuration it is necessary to define **application.properties** file:

```
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=mysqluser
quarkus.datasource.password=mysqlpw
quarkus.datasource.jdbc.url=jdbc:mysql://localhost/eventuate
quarkus.datasource.jdbc.max-size=16
%postgres.quarkus.datasource.db-kind=postgresql
%postgres.quarkus.datasource.username=eventuate
%postgres.quarkus.datasource.password=eventuate
%postgres.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost/eventuate
%postgres.quarkus.datasource.jdbc.max-size=16
```
and set env variable QUARKUS_PROFILE to postgres.

But it does not work, if do that and run test that use quarkus datasource bean following error appears:
```

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:144)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:956)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:826)
	... 11 more
```

As it seen from error, application still tries to use mysql driver.

If avoid default profiles:

```
%mysql.quarkus.datasource.db-kind=mysql
%mysql.quarkus.datasource.username=mysqluser
%mysql.quarkus.datasource.password=mysqlpw
%mysql.quarkus.datasource.jdbc.url=jdbc:mysql://localhost/eventuate
%mysql.quarkus.datasource.jdbc.max-size=16
%postgres.quarkus.datasource.db-kind=postgresql
%postgres.quarkus.datasource.username=eventuate
%postgres.quarkus.datasource.password=eventuate
%postgres.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost/eventuate
%postgres.quarkus.datasource.jdbc.max-size=16
```

it also does not work (profile is postgres):

```
Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: No bean found for required type [interface javax.sql.DataSource] and qualifiers [[@javax.enterprise.inject.Default()]]
	at io.quarkus.arc.impl.InstanceImpl.bean(InstanceImpl.java:175)
	at io.quarkus.arc.impl.InstanceImpl.getInternal(InstanceImpl.java:196)
	at io.quarkus.arc.impl.InstanceImpl.get(InstanceImpl.java:93)
	at io.eventuate.common.quarkus.jdbc.EventuateCommonJdbcOperationsConfiguration.lambda$eventuateJdbcStatementExecutor$0(EventuateCommonJdbcOperationsConfiguration.java:35)
	at io.eventuate.common.jdbc.EventuateCommonJdbcStatementExecutor.update(EventuateCommonJdbcStatementExecutor.java:69)
	at io.eventuate.common.jdbc.tests.AbstractEventuateCommonJdbcOperationsTest.lambda$testEventuateDuplicateKeyException$0(AbstractEventuateCommonJdbcOperationsTest.java:46)
	at io.eventuate.common.quarkus.jdbc.EventuateQuarkusTransactionTemplate.executeInTransaction(EventuateQuarkusTransactionTemplate.java:12)
	at io.eventuate.common.quarkus.jdbc.EventuateQuarkusTransactionTemplate_Subclass.executeInTransaction$$superaccessor1(EventuateQuarkusTransactionTemplate_Subclass.zig:210)
	at io.eventuate.common.quarkus.jdbc.EventuateQuarkusTransactionTemplate_Subclass$$function$$1.apply(EventuateQuarkusTransactionTemplate_Subclass$$function$$1.zig:33)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:127)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:100)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:53)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:26)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(TransactionalInterceptorRequired_Bean.zig:340)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.eventuate.common.quarkus.jdbc.EventuateQuarkusTransactionTemplate_Subclass.executeInTransaction(EventuateQuarkusTransactionTemplate_Subclass.zig:168)
	at io.eventuate.common.quarkus.jdbc.EventuateQuarkusTransactionTemplate_ClientProxy.executeInTransaction(EventuateQuarkusTransactionTemplate_ClientProxy.zig:205)
	at io.eventuate.common.jdbc.tests.AbstractEventuateCommonJdbcOperationsTest.testEventuateDuplicateKeyException(AbstractEventuateCommonJdbcOperationsTest.java:44)
	at io.eventuate.common.quarkus.jdbc.EventuateCommonJdbcOperationsTest.lambda$testEventuateDuplicateKeyException$0(EventuateCommonJdbcOperationsTest.java:40)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:55)
	... 93 more
```

### Reason

I found following issue: https://stackoverflow.com/questions/63076582/unable-to-use-external-configuration-with-quarkus

According the issue, quarkus.datasource.db-kind cannot be defined/overwritten at the runtime.
There is the proof: https://quarkus.io/guides/all-config#quarkus-datasource_quarkus.datasource.db-kind
quarkus.datasource.db-kind is marked with lock icon, and tooltip says: "fixed at build time"

**Comment by dartartem** [comment]
I found solution:

1) define all connections as named data sources:

```
quarkus.datasource.mysql.db-kind=mysql
quarkus.datasource.mysql.username=mysqluser
quarkus.datasource.mysql.password=mysqlpw
quarkus.datasource.mysql.jdbc.url=jdbc:mysql://localhost/eventuate
quarkus.datasource.mysql.jdbc.max-size=16

quarkus.datasource.postgres.db-kind=postgresql
quarkus.datasource.postgres.username=eventuate
quarkus.datasource.postgres.password=eventuate
quarkus.datasource.postgres.jdbc.url=jdbc:postgresql://localhost/eventuate
quarkus.datasource.postgres.jdbc.max-size=16

quarkus.datasource.mssql.db-kind=mssql
quarkus.datasource.mssql.username=sa
quarkus.datasource.mssql.password=Eventuate123!
quarkus.datasource.mssql.jdbc.url=jdbc:sqlserver://localhost:1433;databaseName=eventuate
quarkus.datasource.mssql.jdbc.max-size=16
```

2) define eventuateDatabase property, that can be configured at the runtime.

3) Create configuration that selects required data source depending on that property:

```
@ApplicationScoped
@Alternative
@Priority(1)
public class DataSourceSelectorConfiguration {

  @Produces
  public DataSource defaultDatasource(@ConfigProperty(name = "eventuateDatabase") String db,
                                      @Named("mysql") Instance<DataSource> mysql,
                                      @Named("postgres") Instance<DataSource> postgres,
                                      @Named("mssql") Instance<DataSource> mssql) {
    if ("mysql".equals(db)) return mysql.get();
    if ("postgres".equals(db)) return postgres.get();
    if ("mssql".equals(db)) return mssql.get();

    throw new RuntimeException("DB not found");
  }
}
```
Tested. It works.

**Comment by cer** [comment]
To be clear: this is a problem for writing tests for eventuate. Ie. It's a problem for us as developers of eventuate. Not as eventuate users.

Your solution defines 3 data sources. Does this mean all 3 database need to be running?

**Comment by cer** [comment]
Also, what other solutions are there? For example, the tests are built and executed by Gradle: what could it do seetup the correct config file.

**Comment by dartartem** [comment]
> To be clear: this is a problem for writing tests for eventuate. Ie. It's a problem for us as developers of eventuate. Not as eventuate users.

Yes. But I think it depends, what if user wants to select database type at runtime?

> Your solution defines 3 data sources. Does this mean all 3 database need to be running?

No, only target database is enough.

> Also, what other solutions are there? For example, the tests are built and executed by Gradle: what could it do seetup the correct config file.

Hm.. I did not think about it in this way. Probably yes, we can somehow configure db-kind using gradle.

**Comment by cer** [comment]
> Yes. But I think it depends, what if user wants to select database type at runtime?
> 
> >

That's up to them to decide how to handle. Eventuate is a framework and should remain neutral.

**Comment by cer** [comment]
> Database should be selected at the build time and it is not clear how to test applications over different databases

This needs some more context and is vague. When exactly does this problem occur? What 'application' is being tested - Aren't you just discussing tests for modules of the Eventuate framework? How about a specific example, e.g. `eventuate-common-xyz/src/tests` needs to be tested with databases A,B,C?

**Comment by cer** [comment]
> Hm.. I did not think about it in this way. Probably yes, we can somehow configure db-kind using gradle.

I don't think this is the best tutorial but I googling found this: https://dzone.com/articles/resource-filtering-gradle - I'd look in the gradle docs for more information

**Comment by dartartem** [comment]
> That's up to them to decide how to handle. Eventuate is a framework and should remain neutral.

I tried to achieve the same behavior that provide spring/micronaut.

You think that I should solve it using gradle instead, right?

> This needs some more context and is vague. When exactly does this problem occur? What 'application' is being tested - Aren't you just discussing tests for modules of the Eventuate framework? How about a specific example, e.g. eventuate-common-xyz/src/tests needs to be tested with databases A,B,C?

I am describing how quarkus works in general, but faced it when tried to test eventuate-common-quarkus-jdbc module.
It can be found here: https://github.com/eventuate-foundation/eventuate-common/tree/49f2e88a8531a37fa1171fa7e242a4272312d1c0

properties file with single database: https://github.com/eventuate-foundation/eventuate-common/blob/49f2e88a8531a37fa1171fa7e242a4272312d1c0/eventuate-common-quarkus-jdbc/src/test/resources/application.properties

In the issue, I also described how I tried to extend this configuration (property file) to work with multiple databases.

**Comment by cer** [comment]
> You think that I should solve it using gradle instead, right?
> 
> >

No. I just think it's important to consider multiple solutions and compare their benefits/drawbacks.

Having tests (not production code) work as you describe seems like a reasonable solution:

* define eventuateDatabase property, that can be configured at the runtime.
* Create configuration that selects required data source depending on that property

Can the properties file and DataSourceSelectorConfiguration be defined once in a gradle module that the tests can use?

**Comment by dartartem** [comment]
> Can the properties file and DataSourceSelectorConfiguration be defined once in a gradle module that the tests can use?

I will check.

**Comment by cer** [comment]
> > Can the properties file and DataSourceSelectorConfiguration be defined once in a gradle module that the tests can use?
> 
> I will check.

That's an important part of the problem: There are multiple test modules in many projects that need to implement the same behavior.

**Comment by dartartem** [comment]
I agree that DataSourceSelectorConfiguration should be in separate module (and I think that it should work).

But are you sure that we need to also define properties in that module?

We specify spring/micronaut properties for each module separately.

**Comment by cer** [comment]
> But are you sure that we need to also define properties in that module?
> 
> We specify spring/micronaut properties for each module separately.

I don't think "We do it is this way" is a good argument.
For example, consider this commit: https://github.com/eventuate-tram/eventuate-tram-core/pull/130 - it's the same change made to multiple files.

The important question is: does each and every module need its own properties file?

**Comment by dartartem** [comment]
> I don't think "We do it is this way" is a good argument.
Sometimes consistency is more important than elegance. 

> The important question is: does each and every module need its own properties file?
Probably we need to change approach everywhere.
In all applications we use more or less same configuration.
Different parts can be overwritten.

**Comment by cer** [comment]
> > I don't think "We do it is this way" is a good argument.
> 
> Sometimes consistency is more important than elegance.
> 

Sure consistency is important.
But when that means copying/pasting an sizeable properties file many times then it's worthwhile reconsidering.

> > The important question is: does each and every module need its own properties file?
> 
> Probably we need to change approach everywhere.
> In all applications we use more or less same configuration.
> Different parts can be overwritten.

The scope of the problem is currently Quarkus test configuration. And the Quarkus code will be its own repositories.

**Comment by dartartem** [comment]
Got it. Thank you.
